// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
  },
  datasource: {
    // CLI operations (migrate, studio) need Neon's DIRECT endpoint — the
    // pooled (-pooler/PgBouncer) URL breaks the migration engine. The app
    // itself still uses the pooled DATABASE_URL (src/config/env.ts).
    url: process.env["DIRECT_DATABASE_URL"] ?? process.env["DATABASE_URL"],
  },
});
